version: '3.7'
services:
  mysql:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=myAppDB

  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: guvenbe/sfg-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: guvenbe/sfg-brewery-config
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'

  inventory-service:
    image: guvenbe/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - mysql
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://172.19.0.2:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      restart: on-failure
  inventory-failover:
    image: guvenbe/mssc-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'

  beer-service:
    image: guvenbe/mssc-brewery-gateway-bg
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - mysql
      - inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://172.19.0.2:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      restart: on-failure
  order-service:
    image: guvenbe/mssc-beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - mysql
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://172.19.0.2:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
      restart: on-failure
  gateway:
    image: guvenbe/mssc-brewery-gateway-bg
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - beer-service
      - order-service
      - inventory-failover
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      restart: on-failure
